@startsalt
scale 2
{
{T!
+**__Metric__**       | **__Value__**       | **__Data Type__**
+ **topic_prefix**    | ""               "" | ""               ""
++ edge_node_id       | ""               "" | ""               ""
+++ device_tokens     | ""               "" | ""               ""
++++ Metric Level 1   | ""               "" | ""               ""
+++++ Metric Level 2  | ""               "" | ""               ""
++++++ Metric Name    | ""               "" | ""               ""
}
}
@endsalt


