@startsalt
scale 2
{
{T!
+**__Metric__**                 | ""           "" | **__Value__**      | **__Data Type__**
+**Acme/Dublin/Packaging**      | /topic_prefix   | ""              "" | ""           ""
++ EdgeNode1                    | /edge_node_id   | ""              "" | ""           ""
+++ Filler                      | /device_tokens  | ""              "" | ""           ""
++++ Running                    | ""           "" | ""        FALSE "" | ""   Boolean ""
++++ Faulted                    | ""           "" | ""        FALSE "" | ""   Boolean ""
++++ Speed                      | ""           "" | ""            0 "" | ""     Int32 ""
++++ Fill                       | ""           "" | ""              "" | ""           ""
+++++ Setpoint                  | ""           "" | ""        500.0 "" | ""     Float ""
+++++ Actual                    | ""           "" | ""          0.0 "" | ""     Float ""
++++ Temperature                | ""           "" | ""         21.5 "" | ""     Float ""
++++ Motor                      | ""           "" | ""              "" | ""           ""
+++++ Run                       | ""           "" | ""        FALSE "" | ""   Boolean ""
+++++ Speed Setpoint            | ""           "" | ""            0 "" | ""     Int32 ""
++++ Properties                 | ""           "" | ""              "" | ""           ""
+++++ Manufacturer              | ""           "" | ""         Acme "" | ""    String ""
}
.
{+
   Everything under Filler is
   Device Process Variables and Metric Tags
}


}

@endsalt
